module.exports = {
  USER_MODEL: require("./users.model"),
  VIDEO_MODEL: require("./video.model"),
  SPONSORS_MODEL: require("./sponsor.model"),

  VIDEO_VIEWS_MODEL: require("./videoViews.model"),
  COMMENT_MODEL: require("./comments.model"),
  PLAYLIST_MODEL: require("./playlist.model"),
  FOLLOWED_PLAYLIST_MODEL: require("./followedPlaylist.model"),
  CATEGORY_MODEL: require("./category.model"),
  ADMIN_MODEL: require("./admin.model"),
  VIDEO_REPORT_MODEL: require("./videoRport.model"),
  NOTIFICATION_MODEL: require("./notification.model"),
  DOT_NOTIFICATION_MODEL: require("./dotNotification.model"),
  ADMIN_NOTIFICATION: require("./adminNotification.model"),
  NOTIFICATION_PREFERENCES_MODEL: require("./notificationPreferences.model"),
  COMMENT_REPORT_MODEL: require("./commentsReport.model"),
  FEEDBACK_MODEL: require("./feedback.model"),
  SPONSOR_ANALYTICS: require("./sponsorAnalytic.model"),
  USER_ACTIVITY_MODEL: require("./activity.model"),
  USER_ADDRESS_MODEL: require("./userAddress.model"),
  VIDEO_LIKE_MODEL: require("./videoAnalytics.model").VideoLike,
  VIDEO_IMPRESSION_MODEL: require("./videoAnalytics.model").VideoImpression,
  VIDEO_WATCH_TIME_MODEL: require("./videoAnalytics.model").VideoWatchTime,
  BUG_REPORT_MODEL : require("./bugReport.model"),
  INSPIRATION_MODEL: require("./inspiration.model"),
};
